CC = g++
DEFAULT_FLAGS = -Wall -Wextra -std=c++14

SOURCE_FILE = binaryTree.cpp
OUT_FILE = binaryTree


default: compile run

compile:
	$(CC) $(SOURCE_FILE) $(DEFAULT_FLAGS) -o $(OUT_FILE)

run:
	./$(OUT_FILE)