default:
	c++ binary_tree.cpp -o binary_tree.o -c
	c++ main.cpp binary_tree.o -o main.out
	./main.out
main:
	c++ binary_tree.o main.cpp -o main.out
	./main.out
all: 
	c++ binary_tree.cpp -o binary_tree.o -c
	c++ binary_tree.o main.cpp -o main.out
	./main.out
